# Configuração do Codecov para RecoLab v2

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        informational: false
    
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: true

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "scripts/**/*"
  - "**/__init__.py"
  - "docs/**/*"