name: Coverage Badge

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    name: Update Coverage Badge
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r backend/requirements-dev.txt
    
    - name: Run tests with coverage
      working-directory: ./backend
      run: |
        pytest tests/ \
          --cov=src \
          --cov-report=xml \
          --cov-report=term
    
    - name: Generate coverage badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: badges
        generate-coverage-badge: true
        coverage-badge-filename: coverage.svg